<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
<style>  
    div.padded {  
      padding-top: 0px;  
      padding-right: 100px;  
      padding-bottom: 0.25in;  
      padding-left: 100px;  
    }  
    body {
        font-weight: 300;
        font-family: 'Open Sans', sans-serif;
        color: #121212;
    }
  h1, h2, h3, h4 {
    font-family: 'Source Sans Pro', sans-serif;
  }
</style> 
<title>Sonthaya Visuthikraisee, Julie Han, and Varsha Ramakrishnan |  CS 184</title>
<meta http-equiv="content-type" content="text/html; charset=utf-8" />
<link rel="stylesheet" type="text/css" href="style.css" media="screen" />
<link href="https://fonts.googleapis.com/css?family=Open+Sans|Source+Sans+Pro" rel="stylesheet">

</head>
<body>
<br />
<h1 align="middle">CS 184: Computer Graphics and Imaging, Spring 2018</h1>
<h1 align="middle">Milestone: A-maze-ing game with corny puns</h1>

    <h2 align="middle">Summary</h2>

    <div class="padded">
        <p>For our final project, we’ll be making an openGL video game. The game will be a first person, 3D maze, in which the player will try to navigate to the maze’s exit. </p>

        <p>Team Members:</p>
        <ul> 
            <li>Sonthaya Visuthikraisee, 26123016</li>
            <li>Julie Han, 26022682</li>
            <li>Varsha Ramakrishnan, 3031797029</li>
        </ul>

<!-- Create a short webpage for your milestone report. This should be about 1 page long if printed. You should briefly summarize what you have accomplished, preliminary results, reflect on progress relative to your plan, and update your work plan as appropriate. You must submit this milestone deliverable (and the final deliverable) on a persistent website that you can choose to keep up after class if you wish to present this work in your portfolio. -->

    <h2 align="middle">Current Progress</h2>
    <p> So far, we have accomplished: </p>
        <ul>
            <li>Familiarizing ourselves with OpenGL basics.</li>
            <ul>
                <li>Generating a window.</li>
                <li>Populating the environment with objects.</li>
                <li>Writing vertex and fragment shaders.</li>
                <li>Mapping textures onto objects.</li>
                <li>Using matrix transformations to alter and move objects.</li>
            </ul>
            <li>Simulating first-person camera movement which allows the player to look at and move around in the world.</li>
            <ul>
                <li>Constraining the player to remain inside the bounds of the maze and at the right height.</li>
            </ul>
            <li>Generating a random maze using DFS.</li>
            <ul>
                <li>Starting with a grid of individually walled-off cells, the algorithm randomly traverses through the cells, removing walls as it goes. It stops the traversal when a cell has no unvisited neighbors (i.e. a dead end has been reached). </li>
                <li> Upon reaching a dead end, the algorithm backtracks until there is a cell with an unvisited neighbor and continues traversing from there. </li>
                <li> The process is repeated until all cells have been visited. </li>
            </ul>
            <li>Gathering resources for our next steps. (Resources linked below). </li>
        </ul>

    <h2 align="middle">Preliminary Results</h2>
    <p> We used the following resources: </p>
    <ul>
        <li> <a href="https://learnopengl.com/Getting-started/Camera">OpenGL tutorial</a> </li>
        <li> <a href="https://rosettacode.org/wiki/Maze_generation#Python">Maze generation code</a> </li>
    </ul>

    <div align="center">
        <table style="width=100%">
            <tr>
                <td>
                    <video src="images/camerademo.mov" controls="controls" width="480" height="360" name="First-person camera movement."> </video>
                    <figcaption align="middle">First-person camera movement.</figcaption>
                </td>
                <td>
                    <img src="images/walltex.jpg" width="480px" height="360"/>
                    <figcaption align="middle">Texture we plan to use for the maze walls.</figcaption>
                </td>                
            </tr>
            <tr>
                <td>
                    <img src="images/maze.PNG" width="480px" />
                    <figcaption align="middle">A random maze generated by the DFS algorithm.</figcaption>
                </td>             
            </tr>            
        </table>
    </div>

    <h2 align="middle">Work Plan</h2>
    <p>Our remaining challenges:</p>
    <ul>
        <li>Implementing our randomly generated maze into OpenGL.</li>
        <ul>
            <li>We will create a grid of 16 x 8 cubes in the environment, as per our maze dimensions.</li>
            <li>Where there are walls, we will map a wall texture onto the cube.</li>
            <li>Where there are no walls, we will leave the cube transparent/invisible.</li>
            <li>For glass walls, we will use THREE cubemap refraction mapping.</li>
            <li>Similarly for reflective walls, we will use THREE cubemap reflection mapping.</li>
        </ul>
        <li>Implementing collision detection to ensure the player doesn't walk through walls.</li>
        <ul>
            <li>Since the maze will be constructed from cubes, we will use bounding boxes and check if the camera position intersects with the boundaries of any of the textured cubes.</li>
            <li>If the player attempts to move into a wall, we will stop the camera by refusing to change the camera's position.</li>
            <li>As invisible cubes are meant to be corridors, we will ignore camera intersections with these and allow players to pass through freely.</li>
        </ul>
        <li>Implementing the laser pointer.</li>
        <ul>
            <li>We have found the following resources to help us in implementing the laser pointer and its physical effects (i.e. passing through glass and bouncing off mirrors). </li>
            <ul>
                <li> <a href="https://www.youtube.com/watch?v=bmblOymqfD8">Video demo + high level overview</a> </li>
                <li> <a href="https://gamecollage.com/how-to/lasers-and-mirrors/">High level overview</a> </li>
            </ul>
            <li>On a high level, we plan on drawing a strip of triangles that traces through the end points of the laser pointer. These triangles will be textured with a glow effect.</li>
            <li>To simulate the light bouncing off reflective surfaces, we will fold/reflect the polygon over itself.</li>
            <li>The light will ignore and simply pass through glass surfaces.</li>
        </ul>
        <li>Implementing user interaction with objects</li>
        <ul>
            <li>The user will be able to pick up and drop objects by pressing/releasing the mouse.</li>
            <li>We will be using this resource to help us with object selection:</li>
            <ul>
                <li> <a href="https://en.wikibooks.org/wiki/OpenGL_Programming/Object_selection">Object selection tutorial</a> </li>
            </ul>
        </ul>
    </ul>

    <p> We are currently about a week behind our originally planned schedule. We have updated the schedule as follows: </p>
    <ul>
        <li> <b>4/23 - 4/24:</b> </li>
        <ul>
            <li>Set up the structure of the maze.</li>
            <li>Start implementing camera-wall collision detection.</li>
        </ul>
        <li> <b>4/25 - 4/26:</b> </li>
        <ul>
            <li>Finish handling camera-wall collisions.</li>
            <li>Implement basic laser pointer (no reflections).</li>
        </ul>
        <li> <b>4/27 - 4/28:</b> </li>
        <ul>
            <li>Implement laser pointer reflections.</li>
            <li>Start implementing player-object interactions.</li>
        </ul>
        <li> <b>4/29 - 4/30:</b> </li>
        <ul>
            <li>Refine player-object interactions.</li>
            <li>Prepare for poster presentation.</li>
        </ul>
        <li> <b>5/1 - 5/4:</b> </li>
        <ul>
            <li>Tying up any loose ends.</li>
            <li>Final video.</li>
            <li>Writeup.</li>
    </ul>

    <h2 align="middle">Presentation Slides</h2>
    <a href="https://docs.google.com/presentation/d/18A6RWoynX8x10vN3lHaGwuzIeagN_B3jkSTHqb1H-lk/edit?usp=sharing">Link to Google Slides here</a>


    <h2 align="middle">Video</h2>
    <a href="https://vimeo.com/266222074">Link to Milestone Video here</a>

    <h2 align="middle">All Resources</h2>
    <ul>
        <li> <a href="https://learnopengl.com/Getting-started/Camera">OpenGL tutorial</a> </li>
        <li> <a href="https://rosettacode.org/wiki/Maze_generation#Python">Maze generation code</a> </li> 
        <li> <a href="https://www.youtube.com/watch?v=bmblOymqfD8">Video demo + high level overview</a> </li>
        <li> <a href="https://gamecollage.com/how-to/lasers-and-mirrors/">High level overview</a> </li> 
        <li> <a href="https://en.wikibooks.org/wiki/OpenGL_Programming/Object_selection">Object selection tutorial</a> </li>
    </ul>




</div>
</body>
</html>




